### PR TITLE
Bump to hugo 0.83.1

### PR DESCRIPTION
**Pull request by seisman**

### CODE REVIEW

**Comment by core-man** [comment]
Do we need line 51-53?

**Comment by seisman** [comment]
I think yes, we need to install GMT from conda-forge, right?

**Comment by core-man** [comment]
I mean preview-pr in this repo, see
>  - name: Change Hugo baseurl so that PR preview works        run: |           sed -i 's#https://seismo-learn.org/#https://seismo-learn.org/sitepreview/seismo-learn/website/${{ github.head_ref }}/#' config/_default/config.toml

**Comment by seisman** [comment]
Yes, gmt china also needs it.

**Review by core-man — APPROVED** [review]

**Pull request merged**
